drop table customer;
drop table customer_name_prefix_cd;

create table customer_name_prefix_cd (
    prefix_cd varchar(2) not null,
	prefix_name varchar(5) not null,
	primary key (prefix_cd)
);
create table customer (
    id bigint generated by default as identity,
	email varchar(64) not null,
	customer_name varchar(64) not null,
	prefix_cd varchar(2),
	primary key (id)
);
alter table customer
    add constraint name_prefix_constraint
    foreign key (prefix_cd)
    references customer_name_prefix_cd;