drop table if exists customer_name_prefix_cd;
drop table if exists customer;
create table customer_name_prefix_cd (
    prefix_cd varchar(2) not null,
	prefix_name varchar(5) not null,
	primary key (prefix_cd)
) ENGINE=InnoDB;
create table customer (
    id bigint generated by default as identity,
	email varchar(64) not null,
	customer_name varchar(64) not null,
	prefix_cd varchar(2),
	primary key (id)
) ENGINE=InnoDB;
alter table customer
    add constraint name_prefix_constraint
    foreign key (prefix_cd)
    references customer_name_prefix_cd;